services:
  nginx:
    build:
      context: ./requirements/nginx/.
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
    restart: always

  wordpress:
    build: ./requirements/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR: ${WP_EDITOR}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mariadb
      DOMAIN_NAME: ${DOMAIN_NAME}
    secrets:
      - mysql_password
      - wp_admin_password
      - wp_editor_password
    networks:
      inception:
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /var/www/html/.setup_done ] || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10

  mariadb:
    build: ./requirements/mariadb/.
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /var/lib/mysql/.initialized ] || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

networks:
  inception:


volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

secrets:
  mysql_password:
    file: ./../secrets/mysql_password.txt
  mysql_root_password:
    file: ./../secrets/mysql_root_password.txt
  wp_admin_password:
    file: ./../secrets/wp_admin_password.txt
  wp_editor_password:
    file: ./../secrets/wp_editor_password.txt
