version: "3.8"

services:
  nginx:
    build: srcs/requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
  wordpress:
    build: srcs/requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
  mariadb:
    build: srcs/requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:

networks:
  inception:

volumes:
  mariadb_data:
  wordpress_data:
