version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - backend

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets/mysql_user_password.txt:/run/secrets/mysql_user_password:ro
      - ./secrets/mysql_admin_password.txt:/run/secrets/mysql_admin_password:ro
      - ./requirements/mariadb/init-db.sh:/usr/local/bin/init-db.sh:ro
      - ./requirements/mariadb/init.sql.template:/mnt/init.sql.template:ro
    command: ["/usr/local/bin/init_db.sh"]
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
